// Pre-Raid BiS Gear Sets for all Class/Spec Combinations
// These are equipped when starting a new game or swapping characters

import type { Equipment } from './types';
import type { WoWSpec } from './types';
import {
  // Physical DPS Shared
  LIONHEART_HELM_PREBIS,
  MARK_OF_FORDRING_PREBIS,
  TRUESTRIKE_SHOULDERS_PREBIS,
  CAPE_OF_THE_BLACK_BARON_PREBIS,
  SAVAGE_GLADIATOR_CHAIN_PREBIS,
  BATTLEBORN_ARMBRACES_PREBIS,
  DEVILSAUR_GAUNTLETS_PREBIS,
  BRIGAM_GIRDLE_PREBIS,
  DEVILSAUR_LEGGINGS_PREBIS,
  BLOODMAIL_BOOTS_PREBIS,
  DON_JULIOS_BAND_PREBIS,
  BLACKSTONE_RING_PREBIS,
  HAND_OF_JUSTICE_PREBIS,
  BLACKHANDS_BREADTH_PREBIS,
  DALRENDS_SACRED_CHARGE_PREBIS,
  DALRENDS_TRIBAL_GUARDIAN_PREBIS,
  SATYRS_BOW_PREBIS,
  ARCANITE_REAPER_PREBIS,
  // Tank Gear
  HELM_OF_THE_HOLY_AVENGER_PREBIS,
  MEDALLION_OF_GRAND_MARSHAL_PREBIS,
  STOCKADE_PAULDRONS_PREBIS,
  STONESKIN_GARGOYLE_CAPE_PREBIS,
  DEATHBONE_CHESTPLATE_PREBIS,
  VAMBRACES_OF_THE_SADIST_PREBIS,
  STONEGRIP_GAUNTLETS_PREBIS,
  DEATHBONE_GIRDLE_PREBIS,
  DEATHBONE_LEGGUARDS_PREBIS,
  DEATHBONE_SABATONS_PREBIS,
  NAGLERING_PREBIS,
  MARK_OF_TYRANNY_PREBIS,
  FORCE_OF_WILL_PREBIS,
  SKULLFORGE_REAVER_PREBIS,
  DRACONIAN_DEFLECTOR_PREBIS,
  BLACKCROW_PREBIS,
  // Fury/Prot Warrior Gear
  HELM_OF_THE_EXECUTIONER_PREBIS,
  BREASTPLATE_OF_VALOR_PREBIS,
  LEGPLATES_OF_VALOR_PREBIS,
  BOOTS_OF_VALOR_PREBIS,
  PAINWEAVER_BAND_PREBIS,
  RUNE_OF_THE_GUARD_CAPTAIN_PREBIS,
  // Caster DPS Gear
  CRIMSON_FELT_HAT_PREBIS,
  CHOKER_OF_THE_FIRE_LORD_PREBIS,
  KENTIC_AMICE_PREBIS,
  ARCHIVIST_CAPE_PREBIS,
  ROBE_OF_WINTER_NIGHT_PREBIS,
  ROBE_OF_THE_VOID_PREBIS,
  ROBE_OF_THE_ARCHMAGE_PREBIS,
  SUBLIME_WRISTGUARDS_PREBIS,
  HANDS_OF_POWER_PREBIS,
  BANTHOK_SASH_PREBIS,
  SKYSHROUD_LEGGINGS_PREBIS,
  OMNICAST_BOOTS_PREBIS,
  FREEZING_BAND_PREBIS,
  RING_OF_SPELL_POWER_PREBIS,
  BRIARWOOD_REED_PREBIS,
  EYE_OF_THE_BEAST_PREBIS,
  WITCHBLADE_PREBIS,
  SPIRIT_OF_AQUEMENTAS_PREBIS,
  BONECREEPER_STYLUS_PREBIS,
  // Healer Gear
  CASSANDRAS_GRACE_PREBIS,
  ANIMATED_CHAIN_NECKLACE_PREBIS,
  LIVING_SHOULDERS_PREBIS,
  HIDE_OF_THE_WILD_PREBIS,
  TRUEFAITH_VESTMENTS_PREBIS,
  ROBES_OF_THE_EXALTED_PREBIS,
  LOOMGUARD_ARMBRACES_PREBIS,
  HARMONIOUS_GAUNTLETS_PREBIS,
  WHIPVINE_CORD_PREBIS,
  PADRES_TROUSERS_PREBIS,
  BOOTS_OF_THE_FULL_MOON_PREBIS,
  FORDRINGS_SEAL_PREBIS,
  ROSEWINE_CIRCLE_PREBIS,
  SECOND_WIND_PREBIS,
  MINDTAP_TALISMAN_PREBIS,
  HAMMER_OF_GRACE_PREBIS,
  DRAKESTONE_OF_HEALING_PREBIS,
  // Rogue-Specific
  MASK_OF_THE_UNFORGIVEN_PREBIS,
  CADAVEROUS_ARMOR_PREBIS,
  BRACERS_OF_THE_ECLIPSE_PREBIS,
  MUGGERS_BELT_PREBIS,
  PADS_OF_DREAD_WOLF_PREBIS,
  THRASH_BLADE_PREBIS,
  MIRAHS_SONG_PREBIS,
  FELSTRIKER_PREBIS,
  DISTRACTING_DAGGER_PREBIS,
  // Hunter-Specific
  BEASTSTALKERS_BINDINGS_PREBIS,
  WARPWOOD_BINDING_PREBIS,
  WINDREAVER_GREAVES_PREBIS,
  DEVILSAUR_EYE_PREBIS,
  BARBAROUS_BLADE_PREBIS,
  CARAPACE_SPINE_CROSSBOW_PREBIS,
  // Shaman-Specific
  BLOODVINE_VEST_PREBIS,
  BLOODVINE_LEGGINGS_PREBIS,
  BLOODVINE_BOOTS_PREBIS,
  FLURRY_AXE_PREBIS,
  TOTEM_OF_THE_STORM_PREBIS,
  TOTEM_OF_LIFE_PREBIS,
  TOTEM_OF_RAGE_PREBIS,
  // Druid-Specific
  MANUAL_CROWD_PUMMELER_PREBIS,
  IDOL_OF_THE_MOON_PREBIS,
  IDOL_OF_FEROCITY_PREBIS,
  IDOL_OF_BRUTALITY_PREBIS,
  IDOL_OF_REJUVENATION_PREBIS,
  WOLFSHEAD_HELM_PREBIS,
  WARDEN_STAFF_PREBIS,
  // Paladin-Specific
  GAUNTLETS_OF_VALOR_PREBIS,
  LEGPLATES_CHROMATIC_PREBIS,
  LIBRAM_OF_TRUTH_PREBIS,
  LIBRAM_OF_HOPE_PREBIS,
  LIBRAM_OF_FERVOR_PREBIS,
  // Priest-Specific
  DEVOUT_MANTLE_PREBIS,
  WHITEMEND_PANTS_PREBIS,
  DEVOUT_SANDALS_PREBIS,
  // Mage-Specific
  MAGE_SHOULDERS_PREBIS,
  // Warlock-Specific
  FELCLOTH_SHOULDERS_PREBIS,
} from './items';

// =============================================================================
// WARRIOR GEAR SETS
// =============================================================================

const WARRIOR_FURY_SET: Equipment = {
  head: LIONHEART_HELM_PREBIS,
  neck: MARK_OF_FORDRING_PREBIS,
  shoulders: TRUESTRIKE_SHOULDERS_PREBIS,
  back: CAPE_OF_THE_BLACK_BARON_PREBIS,
  chest: SAVAGE_GLADIATOR_CHAIN_PREBIS,
  wrist: BATTLEBORN_ARMBRACES_PREBIS,
  hands: DEVILSAUR_GAUNTLETS_PREBIS,
  waist: BRIGAM_GIRDLE_PREBIS,
  legs: DEVILSAUR_LEGGINGS_PREBIS,
  feet: BLOODMAIL_BOOTS_PREBIS,
  ring1: DON_JULIOS_BAND_PREBIS,
  ring2: BLACKSTONE_RING_PREBIS,
  trinket1: HAND_OF_JUSTICE_PREBIS,
  trinket2: BLACKHANDS_BREADTH_PREBIS,
  weapon: DALRENDS_SACRED_CHARGE_PREBIS,
  offhand: DALRENDS_TRIBAL_GUARDIAN_PREBIS,
  ranged: SATYRS_BOW_PREBIS,
};

const WARRIOR_ARMS_SET: Equipment = {
  head: LIONHEART_HELM_PREBIS,
  neck: MARK_OF_FORDRING_PREBIS,
  shoulders: TRUESTRIKE_SHOULDERS_PREBIS,
  back: CAPE_OF_THE_BLACK_BARON_PREBIS,
  chest: SAVAGE_GLADIATOR_CHAIN_PREBIS,
  wrist: BATTLEBORN_ARMBRACES_PREBIS,
  hands: DEVILSAUR_GAUNTLETS_PREBIS,
  waist: BRIGAM_GIRDLE_PREBIS,
  legs: DEVILSAUR_LEGGINGS_PREBIS,
  feet: BLOODMAIL_BOOTS_PREBIS,
  ring1: DON_JULIOS_BAND_PREBIS,
  ring2: BLACKSTONE_RING_PREBIS,
  trinket1: HAND_OF_JUSTICE_PREBIS,
  trinket2: BLACKHANDS_BREADTH_PREBIS,
  weapon: ARCANITE_REAPER_PREBIS,
  offhand: null,
  ranged: SATYRS_BOW_PREBIS,
};

const WARRIOR_PROTECTION_SET: Equipment = {
  head: HELM_OF_THE_HOLY_AVENGER_PREBIS,
  neck: MEDALLION_OF_GRAND_MARSHAL_PREBIS,
  shoulders: STOCKADE_PAULDRONS_PREBIS,
  back: STONESKIN_GARGOYLE_CAPE_PREBIS,
  chest: DEATHBONE_CHESTPLATE_PREBIS,
  wrist: VAMBRACES_OF_THE_SADIST_PREBIS,
  hands: STONEGRIP_GAUNTLETS_PREBIS,
  waist: DEATHBONE_GIRDLE_PREBIS,
  legs: DEATHBONE_LEGGUARDS_PREBIS,
  feet: DEATHBONE_SABATONS_PREBIS,
  ring1: NAGLERING_PREBIS,
  ring2: BLACKSTONE_RING_PREBIS,
  trinket1: MARK_OF_TYRANNY_PREBIS,
  trinket2: FORCE_OF_WILL_PREBIS,
  weapon: SKULLFORGE_REAVER_PREBIS,
  offhand: DRACONIAN_DEFLECTOR_PREBIS,
  ranged: BLACKCROW_PREBIS,
};

const WARRIOR_FURY_PROT_SET: Equipment = {
  head: HELM_OF_THE_EXECUTIONER_PREBIS,
  neck: MARK_OF_FORDRING_PREBIS,
  shoulders: TRUESTRIKE_SHOULDERS_PREBIS,
  back: CAPE_OF_THE_BLACK_BARON_PREBIS,
  chest: BREASTPLATE_OF_VALOR_PREBIS,
  wrist: BATTLEBORN_ARMBRACES_PREBIS,
  hands: GAUNTLETS_OF_VALOR_PREBIS,
  waist: BRIGAM_GIRDLE_PREBIS,
  legs: LEGPLATES_OF_VALOR_PREBIS,
  feet: BOOTS_OF_VALOR_PREBIS,
  ring1: PAINWEAVER_BAND_PREBIS,
  ring2: BLACKSTONE_RING_PREBIS,
  trinket1: RUNE_OF_THE_GUARD_CAPTAIN_PREBIS,
  trinket2: BLACKHANDS_BREADTH_PREBIS,
  weapon: DALRENDS_SACRED_CHARGE_PREBIS,
  offhand: DALRENDS_TRIBAL_GUARDIAN_PREBIS,
  ranged: BLACKCROW_PREBIS,
};

// =============================================================================
// PALADIN GEAR SETS
// =============================================================================

const PALADIN_HOLY_SET: Equipment = {
  head: CASSANDRAS_GRACE_PREBIS,
  neck: ANIMATED_CHAIN_NECKLACE_PREBIS,
  shoulders: LIVING_SHOULDERS_PREBIS,
  back: HIDE_OF_THE_WILD_PREBIS,
  chest: ROBES_OF_THE_EXALTED_PREBIS,
  wrist: LOOMGUARD_ARMBRACES_PREBIS,
  hands: HARMONIOUS_GAUNTLETS_PREBIS,
  waist: WHIPVINE_CORD_PREBIS,
  legs: PADRES_TROUSERS_PREBIS,
  feet: BOOTS_OF_THE_FULL_MOON_PREBIS,
  ring1: FORDRINGS_SEAL_PREBIS,
  ring2: ROSEWINE_CIRCLE_PREBIS,
  trinket1: SECOND_WIND_PREBIS,
  trinket2: MINDTAP_TALISMAN_PREBIS,
  weapon: HAMMER_OF_GRACE_PREBIS,
  offhand: DRAKESTONE_OF_HEALING_PREBIS,
  ranged: LIBRAM_OF_HOPE_PREBIS,
};

const PALADIN_PROTECTION_SET: Equipment = {
  head: HELM_OF_THE_HOLY_AVENGER_PREBIS,
  neck: MEDALLION_OF_GRAND_MARSHAL_PREBIS,
  shoulders: STOCKADE_PAULDRONS_PREBIS,
  back: STONESKIN_GARGOYLE_CAPE_PREBIS,
  chest: DEATHBONE_CHESTPLATE_PREBIS,
  wrist: VAMBRACES_OF_THE_SADIST_PREBIS,
  hands: GAUNTLETS_OF_VALOR_PREBIS,
  waist: DEATHBONE_GIRDLE_PREBIS,
  legs: LEGPLATES_CHROMATIC_PREBIS,
  feet: DEATHBONE_SABATONS_PREBIS,
  ring1: NAGLERING_PREBIS,
  ring2: BLACKSTONE_RING_PREBIS,
  trinket1: MARK_OF_TYRANNY_PREBIS,
  trinket2: FORCE_OF_WILL_PREBIS,
  weapon: SKULLFORGE_REAVER_PREBIS,
  offhand: DRACONIAN_DEFLECTOR_PREBIS,
  ranged: LIBRAM_OF_TRUTH_PREBIS,
};

const PALADIN_RETRIBUTION_SET: Equipment = {
  head: LIONHEART_HELM_PREBIS,
  neck: MARK_OF_FORDRING_PREBIS,
  shoulders: TRUESTRIKE_SHOULDERS_PREBIS,
  back: CAPE_OF_THE_BLACK_BARON_PREBIS,
  chest: SAVAGE_GLADIATOR_CHAIN_PREBIS,
  wrist: BATTLEBORN_ARMBRACES_PREBIS,
  hands: DEVILSAUR_GAUNTLETS_PREBIS,
  waist: BRIGAM_GIRDLE_PREBIS,
  legs: DEVILSAUR_LEGGINGS_PREBIS,
  feet: BLOODMAIL_BOOTS_PREBIS,
  ring1: DON_JULIOS_BAND_PREBIS,
  ring2: BLACKSTONE_RING_PREBIS,
  trinket1: HAND_OF_JUSTICE_PREBIS,
  trinket2: BLACKHANDS_BREADTH_PREBIS,
  weapon: ARCANITE_REAPER_PREBIS,
  offhand: null,
  ranged: LIBRAM_OF_FERVOR_PREBIS,
};

// =============================================================================
// HUNTER GEAR SETS
// =============================================================================

const HUNTER_SET: Equipment = {
  head: LIONHEART_HELM_PREBIS,
  neck: MARK_OF_FORDRING_PREBIS,
  shoulders: TRUESTRIKE_SHOULDERS_PREBIS,
  back: CAPE_OF_THE_BLACK_BARON_PREBIS,
  chest: SAVAGE_GLADIATOR_CHAIN_PREBIS,
  wrist: BEASTSTALKERS_BINDINGS_PREBIS,
  hands: DEVILSAUR_GAUNTLETS_PREBIS,
  waist: WARPWOOD_BINDING_PREBIS,
  legs: DEVILSAUR_LEGGINGS_PREBIS,
  feet: WINDREAVER_GREAVES_PREBIS,
  ring1: DON_JULIOS_BAND_PREBIS,
  ring2: BLACKSTONE_RING_PREBIS,
  trinket1: HAND_OF_JUSTICE_PREBIS,
  trinket2: DEVILSAUR_EYE_PREBIS,
  weapon: BARBAROUS_BLADE_PREBIS,
  offhand: null,
  ranged: CARAPACE_SPINE_CROSSBOW_PREBIS,
};

// =============================================================================
// ROGUE GEAR SETS
// =============================================================================

const ROGUE_COMBAT_SET: Equipment = {
  head: MASK_OF_THE_UNFORGIVEN_PREBIS,
  neck: MARK_OF_FORDRING_PREBIS,
  shoulders: TRUESTRIKE_SHOULDERS_PREBIS,
  back: CAPE_OF_THE_BLACK_BARON_PREBIS,
  chest: CADAVEROUS_ARMOR_PREBIS,
  wrist: BRACERS_OF_THE_ECLIPSE_PREBIS,
  hands: DEVILSAUR_GAUNTLETS_PREBIS,
  waist: MUGGERS_BELT_PREBIS,
  legs: DEVILSAUR_LEGGINGS_PREBIS,
  feet: PADS_OF_DREAD_WOLF_PREBIS,
  ring1: DON_JULIOS_BAND_PREBIS,
  ring2: BLACKSTONE_RING_PREBIS,
  trinket1: HAND_OF_JUSTICE_PREBIS,
  trinket2: BLACKHANDS_BREADTH_PREBIS,
  weapon: THRASH_BLADE_PREBIS,
  offhand: MIRAHS_SONG_PREBIS,
  ranged: SATYRS_BOW_PREBIS,
};

const ROGUE_ASSASSINATION_SET: Equipment = {
  head: MASK_OF_THE_UNFORGIVEN_PREBIS,
  neck: MARK_OF_FORDRING_PREBIS,
  shoulders: TRUESTRIKE_SHOULDERS_PREBIS,
  back: CAPE_OF_THE_BLACK_BARON_PREBIS,
  chest: CADAVEROUS_ARMOR_PREBIS,
  wrist: BRACERS_OF_THE_ECLIPSE_PREBIS,
  hands: DEVILSAUR_GAUNTLETS_PREBIS,
  waist: MUGGERS_BELT_PREBIS,
  legs: DEVILSAUR_LEGGINGS_PREBIS,
  feet: PADS_OF_DREAD_WOLF_PREBIS,
  ring1: DON_JULIOS_BAND_PREBIS,
  ring2: BLACKSTONE_RING_PREBIS,
  trinket1: HAND_OF_JUSTICE_PREBIS,
  trinket2: BLACKHANDS_BREADTH_PREBIS,
  weapon: FELSTRIKER_PREBIS,
  offhand: DISTRACTING_DAGGER_PREBIS,
  ranged: SATYRS_BOW_PREBIS,
};

const ROGUE_SUBTLETY_SET: Equipment = {
  ...ROGUE_COMBAT_SET, // Subtlety uses similar gear
};

// =============================================================================
// PRIEST GEAR SETS
// =============================================================================

const PRIEST_HOLY_SET: Equipment = {
  head: CASSANDRAS_GRACE_PREBIS,
  neck: ANIMATED_CHAIN_NECKLACE_PREBIS,
  shoulders: DEVOUT_MANTLE_PREBIS,
  back: HIDE_OF_THE_WILD_PREBIS,
  chest: TRUEFAITH_VESTMENTS_PREBIS,
  wrist: LOOMGUARD_ARMBRACES_PREBIS,
  hands: HARMONIOUS_GAUNTLETS_PREBIS,
  waist: WHIPVINE_CORD_PREBIS,
  legs: WHITEMEND_PANTS_PREBIS,
  feet: DEVOUT_SANDALS_PREBIS,
  ring1: FORDRINGS_SEAL_PREBIS,
  ring2: ROSEWINE_CIRCLE_PREBIS,
  trinket1: SECOND_WIND_PREBIS,
  trinket2: MINDTAP_TALISMAN_PREBIS,
  weapon: HAMMER_OF_GRACE_PREBIS,
  offhand: DRAKESTONE_OF_HEALING_PREBIS,
  ranged: BONECREEPER_STYLUS_PREBIS,
};

const PRIEST_DISCIPLINE_SET: Equipment = {
  ...PRIEST_HOLY_SET, // Discipline uses same healing gear
};

const PRIEST_SHADOW_SET: Equipment = {
  head: CRIMSON_FELT_HAT_PREBIS,
  neck: CHOKER_OF_THE_FIRE_LORD_PREBIS,
  shoulders: KENTIC_AMICE_PREBIS,
  back: ARCHIVIST_CAPE_PREBIS,
  chest: ROBE_OF_WINTER_NIGHT_PREBIS,
  wrist: SUBLIME_WRISTGUARDS_PREBIS,
  hands: HANDS_OF_POWER_PREBIS,
  waist: BANTHOK_SASH_PREBIS,
  legs: SKYSHROUD_LEGGINGS_PREBIS,
  feet: OMNICAST_BOOTS_PREBIS,
  ring1: FREEZING_BAND_PREBIS,
  ring2: RING_OF_SPELL_POWER_PREBIS,
  trinket1: BRIARWOOD_REED_PREBIS,
  trinket2: EYE_OF_THE_BEAST_PREBIS,
  weapon: WITCHBLADE_PREBIS,
  offhand: SPIRIT_OF_AQUEMENTAS_PREBIS,
  ranged: BONECREEPER_STYLUS_PREBIS,
};

// =============================================================================
// SHAMAN GEAR SETS
// =============================================================================

const SHAMAN_ELEMENTAL_SET: Equipment = {
  head: CRIMSON_FELT_HAT_PREBIS,
  neck: CHOKER_OF_THE_FIRE_LORD_PREBIS,
  shoulders: KENTIC_AMICE_PREBIS,
  back: ARCHIVIST_CAPE_PREBIS,
  chest: BLOODVINE_VEST_PREBIS,
  wrist: SUBLIME_WRISTGUARDS_PREBIS,
  hands: HANDS_OF_POWER_PREBIS,
  waist: BANTHOK_SASH_PREBIS,
  legs: BLOODVINE_LEGGINGS_PREBIS,
  feet: BLOODVINE_BOOTS_PREBIS,
  ring1: FREEZING_BAND_PREBIS,
  ring2: RING_OF_SPELL_POWER_PREBIS,
  trinket1: BRIARWOOD_REED_PREBIS,
  trinket2: EYE_OF_THE_BEAST_PREBIS,
  weapon: WITCHBLADE_PREBIS,
  offhand: SPIRIT_OF_AQUEMENTAS_PREBIS,
  ranged: TOTEM_OF_THE_STORM_PREBIS,
};

const SHAMAN_ENHANCEMENT_SET: Equipment = {
  head: LIONHEART_HELM_PREBIS,
  neck: MARK_OF_FORDRING_PREBIS,
  shoulders: TRUESTRIKE_SHOULDERS_PREBIS,
  back: CAPE_OF_THE_BLACK_BARON_PREBIS,
  chest: SAVAGE_GLADIATOR_CHAIN_PREBIS,
  wrist: BATTLEBORN_ARMBRACES_PREBIS,
  hands: DEVILSAUR_GAUNTLETS_PREBIS,
  waist: BRIGAM_GIRDLE_PREBIS,
  legs: DEVILSAUR_LEGGINGS_PREBIS,
  feet: BLOODMAIL_BOOTS_PREBIS,
  ring1: DON_JULIOS_BAND_PREBIS,
  ring2: BLACKSTONE_RING_PREBIS,
  trinket1: HAND_OF_JUSTICE_PREBIS,
  trinket2: BLACKHANDS_BREADTH_PREBIS,
  weapon: FLURRY_AXE_PREBIS,
  offhand: FLURRY_AXE_PREBIS, // Dual-wield
  ranged: TOTEM_OF_RAGE_PREBIS,
};

const SHAMAN_RESTORATION_SET: Equipment = {
  head: CASSANDRAS_GRACE_PREBIS,
  neck: ANIMATED_CHAIN_NECKLACE_PREBIS,
  shoulders: LIVING_SHOULDERS_PREBIS,
  back: HIDE_OF_THE_WILD_PREBIS,
  chest: ROBES_OF_THE_EXALTED_PREBIS,
  wrist: LOOMGUARD_ARMBRACES_PREBIS,
  hands: HARMONIOUS_GAUNTLETS_PREBIS,
  waist: WHIPVINE_CORD_PREBIS,
  legs: PADRES_TROUSERS_PREBIS,
  feet: BOOTS_OF_THE_FULL_MOON_PREBIS,
  ring1: FORDRINGS_SEAL_PREBIS,
  ring2: ROSEWINE_CIRCLE_PREBIS,
  trinket1: SECOND_WIND_PREBIS,
  trinket2: MINDTAP_TALISMAN_PREBIS,
  weapon: HAMMER_OF_GRACE_PREBIS,
  offhand: DRAKESTONE_OF_HEALING_PREBIS,
  ranged: TOTEM_OF_LIFE_PREBIS,
};

// =============================================================================
// MAGE GEAR SETS
// =============================================================================

const MAGE_SET: Equipment = {
  head: CRIMSON_FELT_HAT_PREBIS,
  neck: CHOKER_OF_THE_FIRE_LORD_PREBIS,
  shoulders: MAGE_SHOULDERS_PREBIS,
  back: ARCHIVIST_CAPE_PREBIS,
  chest: ROBE_OF_THE_ARCHMAGE_PREBIS,
  wrist: SUBLIME_WRISTGUARDS_PREBIS,
  hands: HANDS_OF_POWER_PREBIS,
  waist: BANTHOK_SASH_PREBIS,
  legs: SKYSHROUD_LEGGINGS_PREBIS,
  feet: OMNICAST_BOOTS_PREBIS,
  ring1: FREEZING_BAND_PREBIS,
  ring2: RING_OF_SPELL_POWER_PREBIS,
  trinket1: BRIARWOOD_REED_PREBIS,
  trinket2: EYE_OF_THE_BEAST_PREBIS,
  weapon: WITCHBLADE_PREBIS,
  offhand: SPIRIT_OF_AQUEMENTAS_PREBIS,
  ranged: BONECREEPER_STYLUS_PREBIS,
};

// =============================================================================
// WARLOCK GEAR SETS
// =============================================================================

const WARLOCK_SET: Equipment = {
  head: CRIMSON_FELT_HAT_PREBIS,
  neck: CHOKER_OF_THE_FIRE_LORD_PREBIS,
  shoulders: FELCLOTH_SHOULDERS_PREBIS,
  back: ARCHIVIST_CAPE_PREBIS,
  chest: ROBE_OF_THE_VOID_PREBIS,
  wrist: SUBLIME_WRISTGUARDS_PREBIS,
  hands: HANDS_OF_POWER_PREBIS,
  waist: BANTHOK_SASH_PREBIS,
  legs: SKYSHROUD_LEGGINGS_PREBIS,
  feet: OMNICAST_BOOTS_PREBIS,
  ring1: FREEZING_BAND_PREBIS,
  ring2: RING_OF_SPELL_POWER_PREBIS,
  trinket1: BRIARWOOD_REED_PREBIS,
  trinket2: EYE_OF_THE_BEAST_PREBIS,
  weapon: WITCHBLADE_PREBIS,
  offhand: SPIRIT_OF_AQUEMENTAS_PREBIS,
  ranged: BONECREEPER_STYLUS_PREBIS,
};

// =============================================================================
// DRUID GEAR SETS
// =============================================================================

const DRUID_BALANCE_SET: Equipment = {
  head: CRIMSON_FELT_HAT_PREBIS,
  neck: CHOKER_OF_THE_FIRE_LORD_PREBIS,
  shoulders: KENTIC_AMICE_PREBIS,
  back: ARCHIVIST_CAPE_PREBIS,
  chest: ROBE_OF_WINTER_NIGHT_PREBIS,
  wrist: SUBLIME_WRISTGUARDS_PREBIS,
  hands: HANDS_OF_POWER_PREBIS,
  waist: BANTHOK_SASH_PREBIS,
  legs: SKYSHROUD_LEGGINGS_PREBIS,
  feet: OMNICAST_BOOTS_PREBIS,
  ring1: FREEZING_BAND_PREBIS,
  ring2: RING_OF_SPELL_POWER_PREBIS,
  trinket1: BRIARWOOD_REED_PREBIS,
  trinket2: EYE_OF_THE_BEAST_PREBIS,
  weapon: WITCHBLADE_PREBIS,
  offhand: SPIRIT_OF_AQUEMENTAS_PREBIS,
  ranged: IDOL_OF_THE_MOON_PREBIS,
};

const DRUID_FERAL_DPS_SET: Equipment = {
  head: WOLFSHEAD_HELM_PREBIS,
  neck: MARK_OF_FORDRING_PREBIS,
  shoulders: TRUESTRIKE_SHOULDERS_PREBIS,
  back: CAPE_OF_THE_BLACK_BARON_PREBIS,
  chest: CADAVEROUS_ARMOR_PREBIS,
  wrist: BRACERS_OF_THE_ECLIPSE_PREBIS,
  hands: DEVILSAUR_GAUNTLETS_PREBIS,
  waist: MUGGERS_BELT_PREBIS,
  legs: DEVILSAUR_LEGGINGS_PREBIS,
  feet: PADS_OF_DREAD_WOLF_PREBIS,
  ring1: DON_JULIOS_BAND_PREBIS,
  ring2: BLACKSTONE_RING_PREBIS,
  trinket1: HAND_OF_JUSTICE_PREBIS,
  trinket2: BLACKHANDS_BREADTH_PREBIS,
  weapon: MANUAL_CROWD_PUMMELER_PREBIS,
  offhand: null,
  ranged: IDOL_OF_FEROCITY_PREBIS,
};

const DRUID_FERAL_TANK_SET: Equipment = {
  head: WOLFSHEAD_HELM_PREBIS,
  neck: MEDALLION_OF_GRAND_MARSHAL_PREBIS,
  shoulders: TRUESTRIKE_SHOULDERS_PREBIS,
  back: STONESKIN_GARGOYLE_CAPE_PREBIS,
  chest: CADAVEROUS_ARMOR_PREBIS,
  wrist: BRACERS_OF_THE_ECLIPSE_PREBIS,
  hands: DEVILSAUR_GAUNTLETS_PREBIS,
  waist: MUGGERS_BELT_PREBIS,
  legs: DEVILSAUR_LEGGINGS_PREBIS,
  feet: PADS_OF_DREAD_WOLF_PREBIS,
  ring1: NAGLERING_PREBIS,
  ring2: BLACKSTONE_RING_PREBIS,
  trinket1: MARK_OF_TYRANNY_PREBIS,
  trinket2: FORCE_OF_WILL_PREBIS,
  weapon: WARDEN_STAFF_PREBIS,
  offhand: null,
  ranged: IDOL_OF_BRUTALITY_PREBIS,
};

const DRUID_RESTORATION_SET: Equipment = {
  head: CASSANDRAS_GRACE_PREBIS,
  neck: ANIMATED_CHAIN_NECKLACE_PREBIS,
  shoulders: LIVING_SHOULDERS_PREBIS,
  back: HIDE_OF_THE_WILD_PREBIS,
  chest: ROBES_OF_THE_EXALTED_PREBIS,
  wrist: LOOMGUARD_ARMBRACES_PREBIS,
  hands: HARMONIOUS_GAUNTLETS_PREBIS,
  waist: WHIPVINE_CORD_PREBIS,
  legs: PADRES_TROUSERS_PREBIS,
  feet: BOOTS_OF_THE_FULL_MOON_PREBIS,
  ring1: FORDRINGS_SEAL_PREBIS,
  ring2: ROSEWINE_CIRCLE_PREBIS,
  trinket1: SECOND_WIND_PREBIS,
  trinket2: MINDTAP_TALISMAN_PREBIS,
  weapon: HAMMER_OF_GRACE_PREBIS,
  offhand: DRAKESTONE_OF_HEALING_PREBIS,
  ranged: IDOL_OF_REJUVENATION_PREBIS,
};

// =============================================================================
// MASTER MAPPING: Spec -> Equipment Set
// =============================================================================

export const PRE_RAID_BIS_SETS: Record<WoWSpec, Equipment> = {
  // Warrior
  fury: WARRIOR_FURY_SET,
  arms: WARRIOR_ARMS_SET,
  fury_prot: WARRIOR_FURY_PROT_SET,
  protection_warrior: WARRIOR_PROTECTION_SET,
  // Paladin
  holy_paladin: PALADIN_HOLY_SET,
  protection_paladin: PALADIN_PROTECTION_SET,
  retribution: PALADIN_RETRIBUTION_SET,
  // Hunter
  beast_mastery: HUNTER_SET,
  marksmanship: HUNTER_SET,
  survival: HUNTER_SET,
  // Rogue
  assassination: ROGUE_ASSASSINATION_SET,
  combat: ROGUE_COMBAT_SET,
  subtlety: ROGUE_SUBTLETY_SET,
  // Priest
  discipline: PRIEST_DISCIPLINE_SET,
  holy_priest: PRIEST_HOLY_SET,
  shadow: PRIEST_SHADOW_SET,
  // Shaman
  elemental: SHAMAN_ELEMENTAL_SET,
  enhancement: SHAMAN_ENHANCEMENT_SET,
  restoration_shaman: SHAMAN_RESTORATION_SET,
  // Mage
  arcane: MAGE_SET,
  fire_mage: MAGE_SET,
  frost_mage: MAGE_SET,
  // Warlock
  affliction: WARLOCK_SET,
  demonology: WARLOCK_SET,
  destruction: WARLOCK_SET,
  // Druid
  balance: DRUID_BALANCE_SET,
  feral_dps: DRUID_FERAL_DPS_SET,
  feral_tank: DRUID_FERAL_TANK_SET,
  restoration: DRUID_RESTORATION_SET,
};

// Helper function to get pre-raid BiS gear for a spec
export function getPreRaidBisForSpec(spec: WoWSpec): Equipment {
  return PRE_RAID_BIS_SETS[spec];
}
